package com.vbuser.genshin.util.handlers;

import com.vbuser.genshin.util.Reference;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public class SoundsHandler {

    //啦啦啦啦啦啦~啦哩啦~啦啦啦哩哩啦

    public static SoundEvent M_0_1;
    public static SoundEvent M_0_2;
    public static SoundEvent M_0_3;
    public static SoundEvent M_0_4;
    public static SoundEvent M_0_5;
    public static SoundEvent M_0_6;
    public static SoundEvent M_0_7;
    public static SoundEvent M_0_8;
    public static SoundEvent M_0_9;
    public static SoundEvent M_0_10;
    public static SoundEvent M_0_11;
    public static SoundEvent M_0_12_1;
    public static SoundEvent M_0_12_2;
    public static SoundEvent M_0_13;
    public static SoundEvent M_0_14;
    public static SoundEvent M_0_15;
    public static SoundEvent M_0_16;
    public static SoundEvent M_0_17;
    public static SoundEvent M_0_18;
    public static SoundEvent M_0_19;
    public static SoundEvent M_0_20;
    public static SoundEvent M_0_21;
    public static SoundEvent M_0_22;
    public static SoundEvent M_0_23;
    public static SoundEvent M_0_24;
    public static SoundEvent M_0_25_1;
    public static SoundEvent M_0_25_2;
    public static SoundEvent M_0_26;
    public static SoundEvent M_0_27;
    public static SoundEvent M_0_28;
    public static SoundEvent M_0_29;
    public static SoundEvent M_0_30;
    public static SoundEvent M_0_31;
    public static SoundEvent M_0_32;
    public static SoundEvent M_0_33;
    public static SoundEvent M_0_34;
    public static SoundEvent M_0_35;
    public static SoundEvent M_0_36;
    public static SoundEvent M_0_37;
    public static SoundEvent M_0_38;
    public static SoundEvent M_0_39;
    public static SoundEvent M_0_40_1;
    public static SoundEvent M_0_40_2;
    public static SoundEvent M_0_41;
    public static SoundEvent M_0_42;
    public static SoundEvent M_0_43;
    public static SoundEvent M_0_44;
    public static SoundEvent M_0_45;
    public static SoundEvent M_0_46;
    public static SoundEvent M_0_47;
    public static SoundEvent M_0_48;
    public static SoundEvent M_0_49;
    public static SoundEvent M_0_50;
    public static SoundEvent M_0_51;
    public static SoundEvent M_0_53;
    public static SoundEvent M_0_54;
    public static SoundEvent M_0_55;
    public static SoundEvent M_0_56;
    public static SoundEvent M_0_57;
    public static SoundEvent M_0_58;
    public static SoundEvent M_0_59;
    public static SoundEvent M_0_60;
    public static SoundEvent M_0_61;
    public static SoundEvent M_0_62;
    public static SoundEvent M_0_63;
    public static SoundEvent M_0_64;
    public static SoundEvent M_0_65;
    public static SoundEvent M_0_66;
    public static SoundEvent M_0_67;
    public static SoundEvent M_0_68;
    public static SoundEvent M_0_69;
    public static SoundEvent M_0_70;
    public static SoundEvent M_0_71;
    public static SoundEvent M_0_72;
    public static SoundEvent M_0_73;
    public static SoundEvent M_0_74;
    public static SoundEvent M_0_75;
    public static SoundEvent M_0_76;
    public static SoundEvent M_0_77;
    public static SoundEvent M_0_78;
    public static SoundEvent M_0_79;
    public static SoundEvent M_0_80;
    public static SoundEvent M_0_81;
    public static SoundEvent M_0_83;
    public static SoundEvent M_0_84;
    public static SoundEvent M_0_85;
    public static SoundEvent M_0_86;
    public static SoundEvent M_0_87;
    public static SoundEvent M_0_88;
    public static SoundEvent M_0_89;
    public static SoundEvent M_0_90;
    public static SoundEvent M_0_91;
    public static SoundEvent M_0_92;
    public static SoundEvent M_0_93;
    public static SoundEvent M_0_94;
    public static SoundEvent M_0_95;
    public static SoundEvent M_0_96;
    public static SoundEvent M_0_97;
    public static SoundEvent M_0_98;
    public static SoundEvent M_0_99;
    public static SoundEvent M_0_100;
    public static SoundEvent M_0_101;
    public static SoundEvent M_0_102;
    public static SoundEvent M_0_103;
    public static SoundEvent M_0_104;
    public static SoundEvent M_0_105;
    public static SoundEvent M_0_106;
    public static SoundEvent TEST;
    public static SoundEvent A_DAY_IN_MONDSTADT;
    public static SoundEvent AN_INTERESTING_LABOUR;
    public static SoundEvent PURE_SKY;

    public static void registerSounds(){
        TEST = registerSound("test");

        M_0_1 = registerSound("main.0.1");
        M_0_2 = registerSound("main.0.2");
        M_0_3 = registerSound("main.0.3");
        M_0_4 = registerSound("main.0.4");
        M_0_5 = registerSound("main.0.5");
        M_0_6 = registerSound("main.0.6");
        M_0_7 = registerSound("main.0.7");
        M_0_8 = registerSound("main.0.8");
        M_0_9 = registerSound("main.0.9");
        M_0_10 = registerSound("main.0.10");
        M_0_11 = registerSound("main.0.11");
        M_0_12_1 = registerSound("main.0.12.a1");
        M_0_12_2 = registerSound("main.0.12.a2");
        M_0_13 = registerSound("main.0.13");
        M_0_14 = registerSound("main.0.14");
        M_0_15 = registerSound("main.0.15");
        M_0_16 = registerSound("main.0.16");
        M_0_17 = registerSound("main.0.17");
        M_0_18 = registerSound("main.0.18");
        M_0_19 = registerSound("main.0.19");
        M_0_20 = registerSound("main.0.20");
        M_0_21 = registerSound("main.0.21");
        M_0_22 = registerSound("main.0.22");
        M_0_23 = registerSound("main.0.23");
        M_0_24 = registerSound("main.0.24");
        M_0_25_1 = registerSound("main.0.25.a1");
        M_0_25_2 = registerSound("main.0.25.a2");
        M_0_26 = registerSound("main.0.26");
        M_0_27 = registerSound("main.0.27");
        M_0_28 = registerSound("main.0.28");
        M_0_29 = registerSound("main.0.29");
        M_0_30 = registerSound("main.0.30");
        M_0_31 = registerSound("main.0.31");
        M_0_32 = registerSound("main.0.32");
        M_0_33 = registerSound("main.0.33");
        M_0_34 = registerSound("main.0.34");
        M_0_35 = registerSound("main.0.35");
        M_0_36 = registerSound("main.0.36");
        M_0_37 = registerSound("main.0.37");
        M_0_38 = registerSound("main.0.38");
        M_0_39 = registerSound("main.0.39");
        M_0_40_1 = registerSound("main.0.40.a1");
        M_0_40_2 = registerSound("main.0.40.a2");
        M_0_41 = registerSound("main.0.41");
        M_0_42 = registerSound("main.0.42");
        M_0_43 = registerSound("main.0.43");
        M_0_44 = registerSound("main.0.44");
        M_0_45 = registerSound("main.0.45");
        M_0_46 = registerSound("main.0.46");
        M_0_47 = registerSound("main.0.47");
        M_0_48 = registerSound("main.0.48");
        M_0_49 = registerSound("main.0.49");
        M_0_50 = registerSound("main.0.50");
        M_0_51 = registerSound("main.0.51");
        M_0_53 = registerSound("main.0.53");
        M_0_54 = registerSound("main.0.54");
        M_0_55 = registerSound("main.0.55");
        M_0_56 = registerSound("main.0.56");
        M_0_57 = registerSound("main.0.57");
        M_0_58 = registerSound("main.0.58");
        M_0_59 = registerSound("main.0.59");
        M_0_60 = registerSound("main.0.60");
        M_0_61 = registerSound("main.0.61");
        M_0_62 = registerSound("main.0.62");
        M_0_63 = registerSound("main.0.63");
        M_0_64 = registerSound("main.0.64");
        M_0_65 = registerSound("main.0.65");
        M_0_66 = registerSound("main.0.66");
        M_0_67 = registerSound("main.0.67");
        M_0_68 = registerSound("main.0.68");
        M_0_69 = registerSound("main.0.69");
        M_0_70 = registerSound("main.0.70");
        M_0_71 = registerSound("main.0.71");
        M_0_72 = registerSound("main.0.72");
        M_0_73 = registerSound("main.0.73");
        M_0_74 = registerSound("main.0.74");
        M_0_75 = registerSound("main.0.75");
        M_0_76 = registerSound("main.0.76");
        M_0_77 = registerSound("main.0.77");
        M_0_78 = registerSound("main.0.78");
        M_0_79 = registerSound("main.0.79");
        M_0_80 = registerSound("main.0.80");
        M_0_81 = registerSound("main.0.81");
        M_0_83 = registerSound("main.0.83");
        M_0_84 = registerSound("main.0.84");
        M_0_85 = registerSound("main.0.85");
        M_0_86 = registerSound("main.0.86");
        M_0_87 = registerSound("main.0.87");
        M_0_88 = registerSound("main.0.88");
        M_0_89 = registerSound("main.0.89");
        M_0_90 = registerSound("main.0.90");
        M_0_91 = registerSound("main.0.91");
        M_0_92 = registerSound("main.0.92");
        M_0_93 = registerSound("main.0.93");
        M_0_94 = registerSound("main.0.94");
        M_0_95 = registerSound("main.0.95");
        M_0_96 = registerSound("main.0.96");
        M_0_97 = registerSound("main.0.97");
        M_0_98 = registerSound("main.0.98");
        M_0_99 = registerSound("main.0.99");
        M_0_100 = registerSound("main.0.100");
        M_0_101 = registerSound("main.0.101");
        M_0_102 = registerSound("main.0.102");
        M_0_103 = registerSound("main.0.103");
        M_0_104 = registerSound("main.0.104");
        M_0_105 = registerSound("main.0.105");
        M_0_106 = registerSound("main.0.106");
        A_DAY_IN_MONDSTADT=registerSound("a_day_in_mondstadt");
        AN_INTERESTING_LABOUR=registerSound("an_interesting_labour");
        PURE_SKY=registerSound("pure_sky");
    }

    private static SoundEvent registerSound(String name){
        ResourceLocation location = new ResourceLocation(Reference.Mod_ID,name);
        SoundEvent event = new SoundEvent(location);
        event.setRegistryName(name);
        ForgeRegistries.SOUND_EVENTS.register(event);
        return event;
    }

}
