package com.vbuser.genshin.init;

import com.vbuser.genshin.Main;
import com.vbuser.genshin.items.ItemBase;
import com.vbuser.genshin.items.ShengYiWuBase;
import net.minecraft.item.Item;

import java.util.ArrayList;
import java.util.List;

@SuppressWarnings("all")
public class ModItems {
    public static final List<Item> ITEMS = new ArrayList<>();
    //-----------------------------------------------------------------------------------------------
    //Artifacts:
    public static final Item MXJ_H = new ShengYiWuBase("mxj_h",1,1,1);
    public static final Item MXJ_M = new ShengYiWuBase("mxj_m",2,1,1);
    public static final Item MXJ_S = new ShengYiWuBase("mxj_s",3,1,1);
    public static final Item MXJ_B = new ShengYiWuBase("mxj_b",4,1,1);
    public static final Item MXJ_T = new ShengYiWuBase("mxj_t",5,1,1);
    public static final Item MXJ_H_E = new ShengYiWuBase("mxj_h_e",1,2,1);
    public static final Item MXJ_M_E = new ShengYiWuBase("mxj_m_e",2,2,1);
    public static final Item MXJ_S_E = new ShengYiWuBase("mxj_s_e",3,2,1);
    public static final Item MXJ_B_E = new ShengYiWuBase("mxj_b_e",4,2,1);
    public static final Item MXJ_T_E = new ShengYiWuBase("mxj_t_e",5,2,1);
    public static final Item MXJ_H_S = new ShengYiWuBase("mxj_h_s",1,3,1);
    public static final Item MXJ_M_S = new ShengYiWuBase("mxj_m_s",2,3,1);
    public static final Item MXJ_S_S = new ShengYiWuBase("mxj_s_s",3,3,1);
    public static final Item MXJ_B_S = new ShengYiWuBase("mxj_b_s",4,3,1);
    public static final Item MXJ_T_S = new ShengYiWuBase("mxj_t_s",5,3,1);
    public static final Item XYE_H = new ShengYiWuBase("xye_h",1,1,2);
    public static final Item XYE_M = new ShengYiWuBase("xye_m",2,1,2);
    public static final Item XYE_S = new ShengYiWuBase("xye_s",3,1,2);
    public static final Item XYE_B = new ShengYiWuBase("xye_b",4,1,2);
    public static final Item XYE_T = new ShengYiWuBase("xye_t",5,1,2);
    public static final Item XYE_H_E = new ShengYiWuBase("xye_h_e",1,2,2);
    public static final Item XYE_M_E = new ShengYiWuBase("xye_m_e",2,2,2);
    public static final Item XYE_S_E = new ShengYiWuBase("xye_s_e",3,2,2);
    public static final Item XYE_B_E = new ShengYiWuBase("xye_b_e",4,2,2);
    public static final Item XYE_T_E = new ShengYiWuBase("xye_t_e",5,2,2);
    public static final Item XYE_H_S = new ShengYiWuBase("xye_h_s",1,3,2);
    public static final Item XYE_M_S = new ShengYiWuBase("xye_m_s",2,3,2);
    public static final Item XYE_S_S = new ShengYiWuBase("xye_s_s",3,3,2);
    public static final Item XYE_B_S = new ShengYiWuBase("xye_b_s",4,3,2);
    public static final Item XYE_T_S = new ShengYiWuBase("xye_t_s",5,3,2);
    public static final Item YY_H = new ShengYiWuBase("yy_h",1,1,3);
    public static final Item YY_M = new ShengYiWuBase("yy_m",2,1,3);
    public static final Item YY_S = new ShengYiWuBase("yy_s",3,1,3);
    public static final Item YY_B = new ShengYiWuBase("yy_b",4,1,3);
    public static final Item YY_T = new ShengYiWuBase("yy_t",5,1,3);
    public static final Item YY_H_E = new ShengYiWuBase("yy_h_e",1,2,3);
    public static final Item YY_M_E = new ShengYiWuBase("yy_m_e",2,2,3);
    public static final Item YY_S_E = new ShengYiWuBase("yy_s_e",3,2,3);
    public static final Item YY_B_E = new ShengYiWuBase("yy_b_e",4,2,3);
    public static final Item YY_T_E = new ShengYiWuBase("yy_t_e",5,2,3);
    public static final Item YY_H_S = new ShengYiWuBase("yy_h_s",1,3,3);
    public static final Item YY_M_S = new ShengYiWuBase("yy_m_s",2,3,3);
    public static final Item YY_S_S = new ShengYiWuBase("yy_s_s",3,3,3);
    public static final Item YY_B_S = new ShengYiWuBase("yy_b_s",4,3,3);
    public static final Item YY_T_S = new ShengYiWuBase("yy_t_s",5,3,3);
    public static final Item XZZX_H_S = new ShengYiWuBase("xzzx_h_s",1,3,4);
    public static final Item XZZX_M_S = new ShengYiWuBase("xzzx_m_s",2,3,4);
    public static final Item XZZX_S_S = new ShengYiWuBase("xzzx_s_s",3,3,4);
    public static final Item XZZX_B_S = new ShengYiWuBase("xzzx_b_s",4,3,4);
    public static final Item XZZX_T_S = new ShengYiWuBase("xzzx_t_s",5,3,4);
    public static final Item XZZX_H_IV = new ShengYiWuBase("xzzx_h_iv",1,4,4);
    public static final Item XZZX_M_IV = new ShengYiWuBase("xzzx_m_iv",2,4,4);
    public static final Item XZZX_S_IV = new ShengYiWuBase("xzzx_s_iv",3,4,4);
    public static final Item XZZX_B_IV = new ShengYiWuBase("xzzx_b_iv",4,4,4);
    public static final Item XZZX_T_IV = new ShengYiWuBase("xzzx_t_iv",5,4,4);
    public static final Item QJ_H_S = new ShengYiWuBase("qj_h_s",1,3,5);
    public static final Item QJ_M_S = new ShengYiWuBase("qj_m_s",2,3,5);
    public static final Item QJ_S_S = new ShengYiWuBase("qj_s_s",3,3,5);
    public static final Item QJ_B_S = new ShengYiWuBase("qj_b_s",4,3,5);
    public static final Item QJ_T_S = new ShengYiWuBase("qj_t_s",5,3,5);
    public static final Item QJ_H_IV = new ShengYiWuBase("qj_h_iv",1,4,5);
    public static final Item QJ_M_IV = new ShengYiWuBase("qj_m_iv",2,4,5);
    public static final Item QJ_S_IV = new ShengYiWuBase("qj_s_iv",3,4,5);
    public static final Item QJ_B_IV = new ShengYiWuBase("qj_b_iv",4,4,5);
    public static final Item QJ_T_IV = new ShengYiWuBase("qj_t_iv",5,4,5);
    public static final Item ZK_H_S = new ShengYiWuBase("zk_h_s",1,3,6);
    public static final Item ZK_M_S = new ShengYiWuBase("zk_m_s",2,3,6);
    public static final Item ZK_S_S = new ShengYiWuBase("zk_s_s",3,3,6);
    public static final Item ZK_B_S = new ShengYiWuBase("zk_b_s",4,3,6);
    public static final Item ZK_T_S = new ShengYiWuBase("zk_t_s",5,3,6);
    public static final Item ZK_H_IV = new ShengYiWuBase("zk_h_iv",1,4,6);
    public static final Item ZK_M_IV = new ShengYiWuBase("zk_m_iv",2,4,6);
    public static final Item ZK_S_IV = new ShengYiWuBase("zk_s_iv",3,4,6);
    public static final Item ZK_B_IV = new ShengYiWuBase("zk_b_iv",4,4,6);
    public static final Item ZK_T_IV = new ShengYiWuBase("zk_t_iv",5,4,6);
    public static final Item JG_H_S = new ShengYiWuBase("jg_h_s",1,3,7);
    public static final Item JG_M_S = new ShengYiWuBase("jg_m_s",2,3,7);
    public static final Item JG_S_S = new ShengYiWuBase("jg_s_s",3,3,7);
    public static final Item JG_B_S = new ShengYiWuBase("jg_b_s",4,3,7);
    public static final Item JG_T_S = new ShengYiWuBase("jg_t_s",5,3,7);
    public static final Item JG_H_IV = new ShengYiWuBase("jg_h_iv",1,4,7);
    public static final Item JG_M_IV = new ShengYiWuBase("jg_m_iv",2,4,7);
    public static final Item JG_S_IV = new ShengYiWuBase("jg_s_iv",3,4,7);
    public static final Item JG_B_IV = new ShengYiWuBase("jg_b_iv",4,4,7);
    public static final Item JG_T_IV = new ShengYiWuBase("jg_t_iv",5,4,7);
    public static final Item LFZ_H_S = new ShengYiWuBase("lfz_h_s",1,3,8);
    public static final Item LFZ_M_S = new ShengYiWuBase("lfz_m_s",2,3,8);
    public static final Item LFZ_S_S = new ShengYiWuBase("lfz_s_s",3,3,8);
    public static final Item LFZ_B_S = new ShengYiWuBase("lfz_b_s",4,3,8);
    public static final Item LFZ_T_S = new ShengYiWuBase("lfz_t_s",5,3,8);
    public static final Item LFZ_H_IV = new ShengYiWuBase("lfz_h_iv",1,4,8);
    public static final Item LFZ_M_IV = new ShengYiWuBase("lfz_m_iv",2,4,8);
    public static final Item LFZ_S_IV = new ShengYiWuBase("lfz_s_iv",3,4,8);
    public static final Item LFZ_B_IV = new ShengYiWuBase("lfz_b_iv",4,4,8);
    public static final Item LFZ_T_IV = new ShengYiWuBase("lfz_t_iv",5,4,8);
    public static final Item SHZX_H_S = new ShengYiWuBase("shzx_h_s",1,3,9);
    public static final Item SHZX_M_S = new ShengYiWuBase("shzx_m_s",2,3,9);
    public static final Item SHZX_S_S = new ShengYiWuBase("shzx_s_s",3,3,9);
    public static final Item SHZX_B_S = new ShengYiWuBase("shzx_b_s",4,3,9);
    public static final Item SHZX_T_S = new ShengYiWuBase("shzx_t_s",5,3,9);
    public static final Item SHZX_H_IV = new ShengYiWuBase("shzx_h_iv",1,4,9);
    public static final Item SHZX_M_IV = new ShengYiWuBase("shzx_m_iv",2,4,9);
    public static final Item SHZX_S_IV = new ShengYiWuBase("shzx_s_iv",3,4,9);
    public static final Item SHZX_B_IV = new ShengYiWuBase("shzx_b_iv",4,4,9);
    public static final Item SHZX_T_IV = new ShengYiWuBase("shzx_t_iv",5,4,9);
    public static final Item YSZX_H_S = new ShengYiWuBase("yszx_h_s",1,3,10);
    public static final Item YSZX_M_S = new ShengYiWuBase("yszx_m_s",2,3,10);
    public static final Item YSZX_S_S = new ShengYiWuBase("yszx_s_s",3,3,10);
    public static final Item YSZX_B_S = new ShengYiWuBase("yszx_b_s",4,3,10);
    public static final Item YSZX_T_S = new ShengYiWuBase("yszx_t_s",5,3,10);
    public static final Item YSZX_H_IV = new ShengYiWuBase("yszx_h_iv",1,4,10);
    public static final Item YSZX_M_IV = new ShengYiWuBase("yszx_m_iv",2,4,10);
    public static final Item YSZX_S_IV = new ShengYiWuBase("yszx_s_iv",3,4,10);
    public static final Item YSZX_B_IV = new ShengYiWuBase("yszx_b_iv",4,4,10);
    public static final Item YSZX_T_IV = new ShengYiWuBase("yszx_t_iv",5,4,10);
    //-----------------------------------------------------------------------------------------------
    //Foods:
    public static final Item YE_GU_JI_ROU_CHUANG = new ItemBase("ye_gu_ji_rou_chuan",Main.SHI_WU);
    public static final Item TI_WA_TE_JIAN_DAN = new ItemBase("ti_wa_te_jian_dan",Main.SHI_WU);
    public static final Item KAO_ROU_PAI = new ItemBase("kao_rou_pai",Main.SHI_WU);
    public static final Item LUO_BO_SHI_SHU_TANG = new ItemBase("luo_bo_shi_shu_tang",Main.SHI_WU);
    public static final Item BAO_CHAO_ROU_PIAN = new ItemBase("bao_chao_rou_pian",Main.SHI_WU);
    public static final Item TIAN_TIAN_HUA_NIANG_JI = new ItemBase("tian_tian_hua_niang_ji",Main.SHI_WU);
    public static final Item MAN_ZU_SHA_LA = new ItemBase("man_zu_sha_la",Main.SHI_WU);
    public static final Item XING_RENG_DOU_FU = new ItemBase("xing_reng_dou_fu",Main.SHI_WU);
    public static final Item SONG_RONG_NIANG_ROU_JUAN = new ItemBase("song_rong_niang_rou_juan",Main.SHI_WU);
    public static final Item YE_GU_JI_ROU_CHUANG_GOOD = new ItemBase("ye_gu_ji_rou_chuan_good",Main.SHI_WU);
    public static final Item TI_WA_TE_JIAN_DAN_GOOD = new ItemBase("ti_wa_te_jian_dan_good",Main.SHI_WU);
    public static final Item KAO_ROU_PAI_GOOD = new ItemBase("kao_rou_pai_good",Main.SHI_WU);
    public static final Item LUO_BO_SHI_SHU_TANG_GOOD = new ItemBase("luo_bo_shi_shu_tang_good",Main.SHI_WU);
    public static final Item BAO_CHAO_ROU_PIAN_GOOD = new ItemBase("bao_chao_rou_pian_good",Main.SHI_WU);
    public static final Item TIAN_TIAN_HUA_NIANG_JI_GOOD = new ItemBase("tian_tian_hua_niang_ji_good",Main.SHI_WU);
    public static final Item MAN_ZU_SHA_LA_GOOD = new ItemBase("man_zu_sha_la_good",Main.SHI_WU);
    public static final Item XING_RENG_DOU_FU_GOOD = new ItemBase("xing_reng_dou_fu_good",Main.SHI_WU);
    public static final Item SONG_RONG_NIANG_ROU_JUAN_GOOD = new ItemBase("song_rong_niang_rou_juan_good",Main.SHI_WU);
    public static final Item YE_GU_JI_ROU_CHUANG_BAD = new ItemBase("ye_gu_ji_rou_chuan_bad",Main.SHI_WU);
    public static final Item TI_WA_TE_JIAN_DAN_BAD = new ItemBase("ti_wa_te_jian_dan_bad",Main.SHI_WU);
    public static final Item KAO_ROU_PAI_BAD = new ItemBase("kao_rou_pai_bad",Main.SHI_WU);
    public static final Item LUO_BO_SHI_SHU_TANG_BAD = new ItemBase("luo_bo_shi_shu_tang_bad",Main.SHI_WU);
    public static final Item BAO_CHAO_ROU_PIAN_BAD = new ItemBase("bao_chao_rou_pian_bad",Main.SHI_WU);
    public static final Item TIAN_TIAN_HUA_NIANG_JI_BAD = new ItemBase("tian_tian_hua_niang_ji_bad",Main.SHI_WU);
    public static final Item MAN_ZU_SHA_LA_BAD = new ItemBase("man_zu_sha_la_bad",Main.SHI_WU);
    public static final Item XING_RENG_DOU_FU_BAD = new ItemBase("xing_reng_dou_fu_bad",Main.SHI_WU);
    public static final Item SONG_RONG_NIANG_ROU_JUAN_BAD = new ItemBase("song_rong_niang_rou_juan_bad",Main.SHI_WU);
    //-----------------------------------------------------------------------------------------------
    //misc
    public static final Item DEBUG_STICK = new ItemBase("debug_stick",Main.JIAN_CAI);
}
